module.exports={
    tableName:'days',
    attributes:{
        weekId:{
            type:'string'
        },
        title:{
            type:'string'
        },
        subtitle:{
            type:'string'
        },
        day:{
            type:'string'
        },
        abstract:{
            type:'boolean'
        },
        date:{
            type:'datetime'
        }
    }
}