module.exports={
    tableName:'periods',
    attributes:{
        dayId:{
            type:'string'
        },
        name:{
            type:'string'
        },
        title:{
            type:'string'
        },
        dynamic:{
            type:'boolean'
        },
        color:{
            type:'string'
        },
        startTime:{
            type:'datetime'
        },
        endTime:{
            type:'datetime'
        }
    }
}